api:
  container_name: "sxapi-demo-openshift-couchbase-api"
  build: api/
  environment:
  - SX_VERBOSE=true
  - SX_DEBUG=true
  - COUCHBASE_SERVICE_HOST=db
  - COUCHBASE_BUCKET=demo
  - COUCHBASE_USER=Administrator
  - COUCHBASE_PASSWORD=Administrator123$
  ports:
    - "8080:8080"
  links:
    - "db:db"
  volumes:
  - "/secure/dev/startx/sxapi-demo-openshift-couchbase/api/app.js:/app/app.js:Z"
  - "/secure/dev/startx/sxapi-demo-openshift-couchbase/api/package.json:/app/package.json:Z"
  - "/secure/dev/startx/sxapi-demo-openshift-couchbase/api/sxapi.json:/app/sxapi.json:Z"
  command: ["/bin/sx-nodejs" , "run"]

www:
  container_name: "sxapi-demo-openshift-couchbase-www"
  build: www/
  environment:
  - SX_VERBOSE=true
  - SX_DEBUG=true
  - DEMO_API=api-demo.apps.startx.fr
  ports:
    - "8081:8080"
  volumes:
  - "/secure/dev/startx/sxapi-demo-openshift-couchbase/www:/app:Z"
  command: ["/bin/sx-nodejs" , "run"]

db:
  container_name: "sxapi-demo-openshift-couchbase-db"
  image: couchbase/server:5.5.0-Mar
  ports:
    - "8091:8091"
    - "8092:8092"
    - "8093:8093"
    - "8094:8094"
    - "11207:11207"
    - "11210:11210"
    - "11211:11211"
    - "18091-18094"

bot-streamer:
  build: bot-streamer/
  container_name: "sxapi-demo-openshift-couchbase-bot-streamer"
  environment:
  - SX_VERBOSE=true
  - SX_DEBUG=true
  - COUCHBASE_SERVICE_HOST=db
  - COUCHBASE_BUCKET=true
  - COUCHBASE_USER=Administrator
  - COUCHBASE_PASSWORD=Administrator123$
  links:
    - "db:db"
  volumes:
  - "/secure/dev/startx/sxapi-demo-openshift-couchbase/bot-streamer/sxapi.json:/conf/sxapi.json:z"
  - "/secure/dev/startx/sxapi-demo-openshift-couchbase/bot-streamer/package.json:/usr/src/app/package.json:z"
  - "/secure/dev/startx/sxapi-demo-openshift-couchbase/bot-streamer/mylib.js:/usr/src/app/mylib.js:z"