kind: Template
apiVersion: v1
metadata:
  name: sxv4-api-admin-template
  annotations:
    openshift.io/display-name: ${SCOPE} - ${SERVICE} Admin template
    openshift.io/documentation-url: https://github.com/startxfr/sxv4/blob/dev/README.md
    openshift.io/support-url: https://github.com/startxfr/sxv4/issues/new
    openshift.io/generated-by: STARTX
    openshift.io/provider-display-name: STARTX
    description: Template for setting the API admin setup for the STARTX v4 Information System
    iconClass: icon-gear
    tags: startx,openshift,operator,crd,admin
  labels:
    provider: startx
    component: api
    template: sxv4-api-admin-template
message: |-
  Admin account for ${SERVICE} will be soon deployed in project ${ENV}-${SCOPE}.
  Monitor the deployement for application availability and
  Follow created route to browse running application

  Scope          : ${SCOPE}
  Environment    : ${ENV}
  Service        : ${SERVICE}
  Micro-services : couchbase
  
labels:
  provider: startx
  component: api
  template: sxv4-api-admin-template
objects:
- kind: CustomResourceDefinition
  apiVersion: apiextensions.k8s.io/v1beta1
  metadata:
    name: couchbaseclusters.couchbase.com
    namespace: "${ENV}-${SCOPE}"
    annotations:
      openshift.io/display-name: ${SCOPE} - ${SERVICE} CouchbaseCluster CRD
      openshift.io/generated-by: STARTX
  spec:
    group: couchbase.com
    names:
      kind: CouchbaseCluster
      plural: couchbaseclusters
      shortNames:
      - couchbase
      - cbc
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              adminConsoleServices:
                items:
                  enum:
                  - data
                  - index
                  - query
                  - search
                  - eventing
                  - analytics
                  type: string
                type: array
              antiAffinity:
                type: boolean
              authSecret:
                minLength: 1
                type: string
              baseImage:
                type: string
              buckets:
                items:
                  properties:
                    conflictResolution:
                      enum:
                      - seqno
                      - lww
                      type: string
                    enableFlush:
                      type: boolean
                    enableIndexReplica:
                      type: boolean
                    evictionPolicy:
                      enum:
                      - valueOnly
                      - fullEviction
                      - noEviction
                      - nruEviction
                      type: string
                    ioPriority:
                      enum:
                      - high
                      - low
                      type: string
                    memoryQuota:
                      minimum: 100
                      type: integer
                    name:
                      pattern: ^[a-zA-Z0-9._\-%]*$
                      type: string
                    replicas:
                      maximum: 3
                      minimum: 0
                      type: integer
                    type:
                      enum:
                      - couchbase
                      - ephemeral
                      - memcached
                      type: string
                  required:
                  - name
                  - type
                  - memoryQuota
                  type: object
                type: array
              cluster:
                properties:
                  analyticsServiceMemoryQuota:
                    minimum: 1024
                    type: integer
                  autoFailoverMaxCount:
                    maximum: 3
                    minimum: 1
                    type: integer
                  autoFailoverOnDataDiskIssues:
                    type: boolean
                  autoFailoverOnDataDiskIssuesTimePeriod:
                    maximum: 3600
                    minimum: 5
                    type: integer
                  autoFailoverServerGroup:
                    type: boolean
                  autoFailoverTimeout:
                    maximum: 3600
                    minimum: 5
                    type: integer
                  clusterName:
                    type: string
                  dataServiceMemoryQuota:
                    minimum: 256
                    type: integer
                  eventingServiceMemoryQuota:
                    minimum: 256
                    type: integer
                  indexServiceMemoryQuota:
                    minimum: 256
                    type: integer
                  indexStorageSetting:
                    enum:
                    - plasma
                    - memory_optimized
                    type: string
                  searchServiceMemoryQuota:
                    minimum: 256
                    type: integer
                required:
                - dataServiceMemoryQuota
                - indexServiceMemoryQuota
                - searchServiceMemoryQuota
                - eventingServiceMemoryQuota
                - analyticsServiceMemoryQuota
                - indexStorageSetting
                - autoFailoverTimeout
                - autoFailoverMaxCount
                type: object
              disableBucketManagement:
                type: boolean
              exposeAdminConsole:
                type: boolean
              exposedFeatures:
                items:
                  enum:
                  - admin
                  - xdcr
                  - client
                  type: string
                type: array
              logRetentionCount:
                minimum: 0
                type: integer
              logRetentionTime:
                pattern: ^\d+(ns|us|ms|s|m|h)$
                type: string
              paused:
                type: boolean
              serverGroups:
                items:
                  type: string
                type: array
              servers:
                items:
                  properties:
                    name:
                      minLength: 1
                      pattern: ^[-_a-zA-Z0-9]+$
                      type: string
                    pod:
                      properties:
                        automountServiceAccountToken:
                          type: boolean
                        couchbaseEnv:
                          items:
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        labels:
                          type: object
                        nodeSelector:
                          type: object
                        resources:
                          properties:
                            limits:
                              properties:
                                cpu:
                                  type: string
                                memory:
                                  type: string
                                storage:
                                  type: string
                              type: object
                            requests:
                              properties:
                                cpu:
                                  type: string
                                memory:
                                  type: string
                                storage:
                                  type: string
                              type: object
                          type: object
                        tolerations:
                          items:
                            properties:
                              effect:
                                type: string
                              key:
                                type: string
                              operator:
                                type: string
                              tolerationSeconds:
                                type: integer
                              value:
                                type: string
                            required:
                            - key
                            - operator
                            - value
                            - effect
                            type: object
                          type: array
                        volumeMounts:
                          properties:
                            analytics:
                              items:
                                type: string
                              type: array
                            data:
                              type: string
                            default:
                              type: string
                            index:
                              type: string
                            logs:
                              type: string
                          type: object
                      type: object
                    serverGroups:
                      items:
                        type: string
                      type: array
                    services:
                      items:
                        enum:
                        - data
                        - index
                        - query
                        - search
                        - eventing
                        - analytics
                        type: string
                      minLength: 1
                      type: array
                    size:
                      minimum: 1
                      type: integer
                  required:
                  - size
                  - name
                  - services
                  type: object
                minLength: 1
                type: array
              softwareUpdateNotifications:
                type: boolean
              tls:
                properties:
                  static:
                    properties:
                      member:
                        properties:
                          serverSecret:
                            type: string
                        type: object
                      operatorSecret:
                        type: string
                    type: object
                type: object
              version:
                pattern: ^([\w\d]+-)?\d+\.\d+.\d+(-[\w\d]+)?$
                type: string
              volumeClaimTemplates:
                items:
                  properties:
                    metadata:
                      properties:
                        name:
                          type: string
                      required:
                      - name
                      type: object
                    spec:
                      properties:
                        resources:
                          properties:
                            limits:
                              properties:
                                storage:
                                  type: string
                              required:
                              - storage
                              type: object
                            requests:
                              properties:
                                storage:
                                  type: string
                              required:
                              - storage
                              type: object
                          type: object
                        storageClassName:
                          type: string
                      required:
                      - resources
                      - storageClassName
                      type: object
                  required:
                  - metadata
                  - spec
                  type: object
                type: array
            required:
            - baseImage
            - version
            - authSecret
            - cluster
            - servers
    version: v1    
- kind: Secret
  apiVersion: v1
  type: kubernetes.io/dockerconfigjson
  metadata:
    name: ${SERVICE}-rhn-auth
    namespace: "${ENV}-${SCOPE}"
    annotations:
      openshift.io/display-name: ${SCOPE} - ${SERVICE} Redhat Registry connection credentials
      openshift.io/generated-by: STARTX
      template.openshift.io/expose-username: "{.data['RHN_USER']}"
      template.openshift.io/expose-password: "{.data['RHN_PASSWORD']}"
    labels:
      scope: "${SCOPE}"
      environement: "${ENV}"
      app: "${SERVICE}"
  stringData:
    .dockerconfigjson: "{\"auths\":{\"registry.connect.redhat.com\":{\"username\":\"${RHN_USER}\",\"password\":\"${RHN_PASSWORD}\",\"email\":\"cl@startx.fr\"}}}"
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: "couchbase-operator"
    namespace: "${ENV}-${SCOPE}"
    annotations:
      openshift.io/display-name: ${SCOPE} - ${SERVICE} "couchbase-operator" Cluster role
      openshift.io/generated-by: STARTX
  rules:
  - apiGroups:
    - couchbase.com
    resources:
    - couchbaseclusters
    verbs:
    - "*"
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - "get"
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - "*"
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - secrets
    verbs:
    - "*"
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    verbs:
    - "get"
    - "watch"
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - "*"
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: couchbasecluster
    namespace: "${ENV}-${SCOPE}"
    annotations:
      openshift.io/display-name: ${SCOPE} - ${SERVICE} couchbasecluster ClusterRole
      openshift.io/generated-by: STARTX
  rules:
  - apiGroups:
    - couchbase.com
    resources:
    - couchbaseclusters
    verbs:
    - "*"
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: "${SERVICE}-couchbase-operator"
    namespace: "${ENV}-${SCOPE}"
    annotations:
      openshift.io/display-name: ${SCOPE} - ${SERVICE} ${SERVICE}-couchbase-operator ServiceAccount
      openshift.io/generated-by: STARTX
  imagePullSecrets:
  - name: ${SERVICE}-rhn-auth
- kind: ClusterRoleBinding
  apiVersion: authorization.openshift.io/v1
  groupNames: null
  metadata:
    name: "${SERVICE}-couchbase-operator-rolebinding"
    namespace: "${ENV}-${SCOPE}"
    annotations:
      openshift.io/display-name: ${SCOPE} - ${SERVICE} ${SERVICE}-couchbase-operator-rolebinding ClusterRoleBinding
      openshift.io/generated-by: STARTX
  roleRef:
    name: "couchbase-operator"
  subjects:
  - kind: ServiceAccount
    name: "${SERVICE}-couchbase-operator"
    namespace: "${ENV}-${SCOPE}"
  userNames:
  - "system:serviceaccount:${ENV}-${SCOPE}:${SERVICE}-couchbase-operator"  
- kind: RoleBinding
  apiVersion: authorization.openshift.io/v1
  metadata:
    name: ${SERVICE}-couchbasecluster-developer-rolebinding
    namespace: "${ENV}-${SCOPE}"
    annotations:
      openshift.io/display-name: ${SCOPE} - ${SERVICE} Developer Role binding
      openshift.io/generated-by: STARTX
  roleRef:
    name: couchbasecluster
  subjects:
  - kind: User
    name: developer
  userNames:
  - developer
parameters:
- name: SCOPE
  displayName: Project scope
  description: "Project scope (ex: sxv4)"
  value: couchbase
#  value: sxv4
  required: true
- name: ENV
  displayName: Project environement
  description: "Project environment (ex: dev, test or prod)"
  value: dev
  required: true
- name: SERVICE
  displayName: Project service
  description: "Project service"
  value: api
  required: true
- name: RHN_USER
  displayName: RHN container access user
  description: Redhat Network access user to the RH container catalog
  required: true
- name: RHN_PASSWORD
  displayName: RHN container access password
  description: Redhat Network access password to the Rh container catalog
  required: true